### ISSUE TITLE
What is a "small file"?

### ISSUE THREAD

**Issue by NobodyXu** [chriskuehl/docker-storage-benchmark#2]
Your test is quite usefull for me, since I want to use a union fs to mount /usr/local.

But what is frustrating to me is your categorization of "big file" and "small file". I saw no definition in your repository of what is a "small file".

**Comment by asottile** [comment]
Here's where those get set up:

https://github.com/chriskuehl/docker-storage-benchmark/blob/949ab59c6425bc0f888969f5d51e732cb455638e/Dockerfile#L27-L37

Found it via `git grep 'small file'`

**Comment by NobodyXu** [comment]
Thank you very much.
